// Command planstatus regenerates docs/plan/STATUS.md from the YAML frontmatter
// of every task file (docs/plan/phase-*/T*.md). The frontmatter is the single
// source of truth for task status; the board is derived, so the two can never
// drift. Run via `make plan-status`.
//
// It reads only the simple, fixed frontmatter keys this plan uses (id, title,
// phase, branch, status, depends_on) with a hand-rolled parser — no YAML
// dependency. The generated table is written between the BEGIN/END markers in
// STATUS.md; everything outside the markers is preserved.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const (
	planDir    = "docs/plan"
	statusFile = "docs/plan/STATUS.md"
	beginMark  = "<!-- BEGIN TASKS (generated by `make plan-status`; do not edit by hand) -->"
	endMark    = "<!-- END TASKS -->"
)

type task struct {
	id        string
	title     string
	phase     string // frontmatter value, e.g. "03-app"
	branch    string
	status    string
	dependsOn []string
}

// num returns the integer part of a task id ("T07" -> 7) for ordering.
func (t task) num() int {
	n, _ := strconv.Atoi(strings.TrimPrefix(t.id, "T"))
	return n
}

var taskFileRE = regexp.MustCompile(`^T\d+-.*\.md$`)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "planstatus:", err)
		os.Exit(1)
	}
}

func run() error {
	tasks, err := collect()
	if err != nil {
		return err
	}
	if len(tasks) == 0 {
		return fmt.Errorf("no task files found under %s", planDir)
	}
	sort.Slice(tasks, func(i, j int) bool { return tasks[i].num() < tasks[j].num() })
	return rewriteStatus(tasks)
}

func collect() ([]task, error) {
	var tasks []task
	err := filepath.WalkDir(planDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !taskFileRE.MatchString(d.Name()) {
			return nil
		}
		t, perr := parse(path)
		if perr != nil {
			return fmt.Errorf("%s: %w", path, perr)
		}
		tasks = append(tasks, t)
		return nil
	})
	return tasks, err
}

// parse extracts the frontmatter block (between the first two "---" lines) and
// reads the keys the board needs.
func parse(path string) (task, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return task{}, err
	}
	lines := strings.Split(string(data), "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return task{}, fmt.Errorf("missing frontmatter opener")
	}
	var t task
	closed := false
	for _, line := range lines[1:] {
		if strings.TrimSpace(line) == "---" {
			closed = true
			break
		}
		key, val, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		val = strings.TrimSpace(val)
		switch key {
		case "id":
			t.id = val
		case "title":
			t.title = val
		case "phase":
			t.phase = val
		case "branch":
			t.branch = val
		case "status":
			t.status = val
		case "depends_on":
			t.dependsOn = parseList(val)
		}
	}
	if !closed {
		return task{}, fmt.Errorf("unterminated frontmatter")
	}
	if t.id == "" || t.status == "" {
		return task{}, fmt.Errorf("missing required frontmatter (id/status)")
	}
	return t, nil
}

// parseList reads an inline YAML flow list: "[T06, T07]" -> ["T06","T07"]; "[]" -> nil.
func parseList(v string) []string {
	v = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(v, "["), "]"))
	if v == "" {
		return nil
	}
	var out []string
	for part := range strings.SplitSeq(v, ",") {
		if p := strings.TrimSpace(part); p != "" {
			out = append(out, p)
		}
	}
	return out
}

// phaseNum strips the descriptive suffix: "03-app" -> "03".
func phaseNum(phase string) string {
	if n, _, ok := strings.Cut(phase, "-"); ok {
		return n
	}
	return phase
}

func rewriteStatus(tasks []task) error {
	data, err := os.ReadFile(statusFile)
	if err != nil {
		return err
	}
	content := string(data)
	bi := strings.Index(content, beginMark)
	ei := strings.Index(content, endMark)
	if bi < 0 || ei < 0 || ei < bi {
		return fmt.Errorf("%s: BEGIN/END markers not found", statusFile)
	}

	var b strings.Builder
	b.WriteString(beginMark)
	b.WriteString("\n| ID | Title | Phase | Branch | Depends on | Status |\n")
	b.WriteString("|----|-------|-------|--------|------------|--------|\n")
	for _, t := range tasks {
		deps := "—"
		if len(t.dependsOn) > 0 {
			deps = strings.Join(t.dependsOn, ", ")
		}
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
			t.id, t.title, phaseNum(t.phase), t.branch, deps, t.status)
	}

	updated := content[:bi] + b.String() + content[ei:]
	if updated == content {
		return nil
	}
	return os.WriteFile(statusFile, []byte(updated), 0o644)
}
